#!/bin/bash

main() {
  check_fmt
  check_vet
  check_staticcheck
}

check_fmt() {
  eval "set -e"
  for file in $(git ls-files '*.go') ; do
    gofmt -s $file | diff -u $file -
  done
  eval "set +e"
}

check_vet() {
  go vet ./...
}

check_staticcheck() {
  staticcheck ./...
}

main "$@"
